server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms-curso
          uri: http://localhost:8081
          predicates:
            - Path=/api/cursos/**
          filters:
            - AddRequestHeader=Usuario, Aaron

        - id: ms-matricula
          uri: http://localhost:8082
          predicates:
            - Path=/api/matriculas/**
          filters:
            - AddRequestHeader=Usuario, Aaron