INSERT INTO CURSO (NOMBRE, CODIGO, CREDITOS) VALUES ('Desarrollo de Aplicaciones Distribuidas', 'DAD101', 4);
INSERT INTO CURSO (NOMBRE, CODIGO, CREDITOS) VALUES ('Base de Datos', 'BD201', 3);
INSERT INTO CURSO (NOMBRE, CODIGO, CREDITOS) VALUES ('Ingenieria de Software', 'IS301', 4);